function messung = importMessung(filename)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   messung = importMessung(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   messung = IMPORTFILE(FILENAME) Reads data of text file FILENAME.
%
% Example:
%   Langzeitmessung = importfile('Langzeitmessung');
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/11/29 17:47:29

%% Initialize variables.
delimiter = ';';
startRow = 3;
endRow = inf;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
messung = table(dataArray{1:end-1}, 'VariableNames', {'Zeit','Kanal_1'});

